INSTRUCTIONS_LOCATION_INDICATOR = "------------------------------------------------------------------\n"
DATA_ENTRIES_LOCATION_INDICATOR = "------------------------------------------------------------------\n"

EXPECTED_REGISTER_IDENTIFIER_LEN = 3
EXPECTED_INSTRUCTION_LEN = 15

INSTRUCTION_CODE_START_IDX = 0
INSTRUCTION_CODE_END_IDX = 5

RZ_START_IDX = 6
RZ_END_IDX = 8

RX_START_IDX = 9
RX_END_IDX = 11

RY_START_IDX = 12
RY_END_IDX = 14

JMP_DESTINATION_START_IDX = 6
JMP_DESTINATION_END_IDX = 14
